import { FunctionComponent } from "react";
import Footer from "../components/Footer";
import MoreButton from "../components/MoreButton";
import Trending from "../components/Trending";
import Collections from "../components/Collections";
import Auction from "../components/Auction";
import ExploreAndCollectNFTsContainer from "../components/ExploreAndCollectNFTsContainer";
import NavigationBar from "../components/NavigationBar";

const LandingV: FunctionComponent = () => {
  return (
    <div className="w-full relative bg-ffffff h-[177.25rem] overflow-hidden">
      <Footer
        navigationWebFooterOnLWidth="100%"
        navigationWebFooterOnLHeight="28.125rem"
        navigationWebFooterOnLPosition="absolute"
        navigationWebFooterOnLRight="0rem"
        navigationWebFooterOnLBottom="0rem"
        navigationWebFooterOnLLeft="0rem"
        lineIconRight="-0.031rem"
        lineIconLeft="0.031rem"
        lineIconHeight="0.063rem"
        buttonsLabelIconTranspRight="6rem"
        buttonsLabelIconTranspBottom="1.313rem"
        buttonsLabelIconTranspWidth="4.563rem"
        buttonsLabelIconTranspHeight="2.875rem"
        linkGap="0.375rem"
        lableFontSize="0.875rem"
        lableLineHeight="1.313rem"
        iconFontSize="1.125rem"
        buttonsIconOutlineRestRight="2rem"
        buttonsIconOutlineRestBottom="1.25rem"
        buttonsIconOutlineRestWidth="2.875rem"
        buttonsIconOutlineRestHeight="2.875rem"
        iconFontSize1="1.125rem"
        linksBottom="2.125rem"
        linksLeft="2rem"
        linksWidth="22.938rem"
        linksHeight="1.125rem"
        allRightsReLeft="13.5rem"
        allRightsReFontSize="0.75rem"
        allRightsReLineHeight="1.125rem"
        privacyPolicyLeft="0rem"
        privacyPolicyFontSize="0.75rem"
        privacyPolicyLineHeight="1.125rem"
        licenseLeft="6.563rem"
        licenseFontSize="0.75rem"
        licenseLineHeight="1.125rem"
        aPILeft="10.813rem"
        aPIFontSize="0.75rem"
        aPILineHeight="1.125rem"
        linksWidth1="7.625rem"
        linksHeight1="13.313rem"
        marketplaceLeft="0rem"
        marketplaceFontSize="1rem"
        marketplaceLineHeight="1.5rem"
        exploreHelpCenterContaineLeft="0rem"
        exploreHelpCenterContaineFontSize="0.875rem"
        exploreHelpCenterContaineLineHeight="2.125rem"
        subscribeTop="4.125rem"
        subscribeLeft="5.063rem"
        subscribeWidth="18.813rem"
        subscribeHeight="5.625rem"
        subscribeToUpdatesLeft="0rem"
        subscribeToUpdatesFontSize="1rem"
        subscribeToUpdatesLineHeight="1.5rem"
        placeholderLeft="1.25rem"
        placeholderFontSize="0.875rem"
        placeholderLineHeight="1.313rem"
        fieldTitleTop="-0.125rem"
        fieldTitleLeft="0rem"
        fieldTitleFontSize="0.75rem"
        fieldTitleLineHeight="1.125rem"
        iconRight="1.125rem"
        iconFontSize2="1.125rem"
        followBottom="9.313rem"
        followLeft="5.031rem"
        followWidth="16.375rem"
        followHeight="5.563rem"
        followUsLeft="0.031rem"
        followUsFontSize="1rem"
        followUsLineHeight="1.5rem"
        buttonsSocialLogoPlacehWidth="1rem"
        buttonsSocialLogoPlacehHeight="1rem"
        buttonsSocialLogoTwittWidth="1rem"
        buttonsSocialLogoTwittHeight="1rem"
        buttonsSocialLogoPinteWidth="1rem"
        buttonsSocialLogoPinteHeight="1rem"
        linksWidth2="6.375rem"
        linksHeight2="15.5rem"
        communityLeft="0rem"
        communityFontSize="1rem"
        communityLineHeight="1.5rem"
        profileFavoritesWaContainLeft="0rem"
        profileFavoritesWaContainFontSize="0.875rem"
        profileFavoritesWaContainLineHeight="2.125rem"
        languageRight="4.813rem"
        languageWidth="19.063rem"
        languageHeight="11.375rem"
        regionLeft="0rem"
        regionFontSize="1rem"
        regionLineHeight="1.5rem"
        buttonsLabelIconTranspRight1="9.188rem"
        buttonsLabelIconTranspWidth1="9.875rem"
        buttonsLabelIconTranspHeight1="2.875rem"
        linkGap1="0.375rem"
        lableFontSize1="0.875rem"
        lableLineHeight1="1.313rem"
        iconFontSize3="1.125rem"
        theWorldsFirstRight="0rem"
        theWorldsFirstBottom="4.438rem"
        theWorldsFirstFontSize="0.875rem"
        theWorldsFirstLineHeight="1.313rem"
        theWorldsFirstWidth="19.063rem"
        theWorldsFirstHeight="4.438rem"
      />
      <MoreButton
        lable="Load More"
        buttonsLabelFilledRestWidth="15.063rem"
        buttonsLabelFilledRestHeight="2.875rem"
        buttonsLabelFilledRestPosition="absolute"
        buttonsLabelFilledRestBottom="31.125rem"
        buttonsLabelFilledRestLeft="calc(50% - 120px)"
        lableLeft="34.77%"
        lableFontSize="0.875rem"
        lableLineHeight="1.313rem"
      />
      <Trending />
      <Collections />
      <Auction />
      <ExploreAndCollectNFTsContainer />
      <NavigationBar
        navigationWebGuestOnLiWidth="90rem"
        navigationWebGuestOnLiHeight="5.25rem"
        navigationWebGuestOnLiPosition="absolute"
        navigationWebGuestOnLiTop="0rem"
        navigationWebGuestOnLiLeft="0rem"
        buttonsLabelFilledRestRight="8.5rem"
        buttonsLabelFilledRestWidth="6.125rem"
        buttonsLabelFilledRestHeight="2.5rem"
        lableFontSize="0.875rem"
        lableLineHeight="1.313rem"
        buttonsLabelFilledRestRight1="2rem"
        buttonsLabelFilledRestWidth1="6.125rem"
        buttonsLabelFilledRestHeight1="2.5rem"
        lableFontSize1="0.875rem"
        lableLineHeight1="1.313rem"
        linksRight="16.938rem"
        linksGap="1.812rem"
        exploreFontSize="1rem"
        exploreLineHeight="1.5rem"
        statsFontSize="1rem"
        statsLineHeight="1.5rem"
        dropsFontSize="1rem"
        dropsLineHeight="1.5rem"
        activityFontSize="1rem"
        activityLineHeight="1.5rem"
        searchLeft="5rem"
        searchWidth="32.438rem"
        searchHeight="2.5rem"
        searchIconLeft="0.938rem"
        searchIconFontSize="1.25rem"
        searchItemsCollecLeft="3rem"
        searchItemsCollecFontSize="0.875rem"
        searchItemsCollecLineHeight="1.313rem"
        elementLogoHiddenLeft="2rem"
        elementLogoHiddenWidth="2.5rem"
        elementLogoHiddenHeight="2.5rem"
      />
    </div>
  );
};

export default LandingV;
