import { FunctionComponent } from "react";
import TopCollectionItem from "./TopCollectionItem";
import CollectionFilterSelected from "./CollectionFilterSelected";
import CollectionFilter from "./CollectionFilter";

export type CollectionsType = {
  className?: string;
};

const Collections: FunctionComponent<CollectionsType> = ({
  className = "",
}) => {
  return (
    <div
      className={`absolute top-[88.688rem] left-[5rem] w-[80rem] h-[18.375rem] text-left text-[1.5rem] text-primary font-heading-h4 ${className}`}
    >
      <div className="absolute top-[calc(50%_-_143px)] left-[0%] font-extrabold">
        Top collections
      </div>
      <div className="absolute h-[74.15%] w-full top-[25.85%] right-[0%] bottom-[0%] left-[0%]">
        <TopCollectionItem
          buttonsSocialLogoFlow="/buttons-social--logo--tezos1.svg"
          price="5344.13 "
          name1="Bored Ape Chemistry Club"
          art="/art@2x.png"
          number="2"
          authorWebItemV1OnLiWidth="32.03%"
          authorWebItemV1OnLiHeight="24.77%"
          authorWebItemV1OnLiPosition="absolute"
          authorWebItemV1OnLiTop="37.61%"
          authorWebItemV1OnLiRight="67.97%"
          authorWebItemV1OnLiBottom="37.61%"
          authorWebItemV1OnLiLeft="0%"
          volumeLeft="6.375rem"
          volumeGap="0.375rem"
          buttonsSocialLogoFlowWidth="1.25rem"
          buttonsSocialLogoFlowHeight="1.25rem"
          priceFontSize="0.875rem"
          priceLineHeight="1.313rem"
          nameLeft="6.375rem"
          nameFontSize="1rem"
          nameLineHeight="1.5rem"
          artIconLeft="1.875rem"
          artIconWidth="3.375rem"
          artIconHeight="3.375rem"
          numberLeft="0rem"
          numberFontSize="0.875rem"
          numberLineHeight="1.313rem"
        />
        <TopCollectionItem
          buttonsSocialLogoFlow="/buttons-social--logo--tezos1.svg"
          price="5344.13 "
          name1="Psychedelics Anonymous"
          art="/art@2x.png"
          number="6"
          authorWebItemV1OnLiWidth="32.03%"
          authorWebItemV1OnLiHeight="24.77%"
          authorWebItemV1OnLiPosition="absolute"
          authorWebItemV1OnLiTop="75.23%"
          authorWebItemV1OnLiRight="34.06%"
          authorWebItemV1OnLiBottom="0%"
          authorWebItemV1OnLiLeft="33.91%"
          volumeLeft="6.375rem"
          volumeGap="0.375rem"
          buttonsSocialLogoFlowWidth="1.25rem"
          buttonsSocialLogoFlowHeight="1.25rem"
          priceFontSize="0.875rem"
          priceLineHeight="1.313rem"
          nameLeft="6.375rem"
          nameFontSize="1rem"
          nameLineHeight="1.5rem"
          artIconLeft="1.875rem"
          artIconWidth="3.375rem"
          artIconHeight="3.375rem"
          numberLeft="0rem"
          numberFontSize="0.875rem"
          numberLineHeight="1.313rem"
        />
        <TopCollectionItem
          buttonsSocialLogoFlow="/buttons-social--logo--tezos1.svg"
          price="6890.34 "
          name1="Free Way to Back Up"
          art="/art@2x.png"
          number="9"
          authorWebItemV1OnLiWidth="32.03%"
          authorWebItemV1OnLiHeight="24.77%"
          authorWebItemV1OnLiPosition="absolute"
          authorWebItemV1OnLiTop="75.23%"
          authorWebItemV1OnLiRight="0%"
          authorWebItemV1OnLiBottom="0%"
          authorWebItemV1OnLiLeft="67.97%"
          volumeLeft="6.375rem"
          volumeGap="0.375rem"
          buttonsSocialLogoFlowWidth="1.25rem"
          buttonsSocialLogoFlowHeight="1.25rem"
          priceFontSize="0.875rem"
          priceLineHeight="1.313rem"
          nameLeft="6.375rem"
          nameFontSize="1rem"
          nameLineHeight="1.5rem"
          artIconLeft="1.875rem"
          artIconWidth="3.375rem"
          artIconHeight="3.375rem"
          numberLeft="0rem"
          numberFontSize="0.875rem"
          numberLineHeight="1.313rem"
        />
        <TopCollectionItem
          buttonsSocialLogoFlow="/buttons-social--logo--tezos1.svg"
          price="4579.40"
          name1="Bored Ape Kennel Club"
          art="/art@2x.png"
          number="5"
          authorWebItemV1OnLiWidth="32.03%"
          authorWebItemV1OnLiHeight="24.77%"
          authorWebItemV1OnLiPosition="absolute"
          authorWebItemV1OnLiTop="37.61%"
          authorWebItemV1OnLiRight="34.06%"
          authorWebItemV1OnLiBottom="37.61%"
          authorWebItemV1OnLiLeft="33.91%"
          volumeLeft="6.375rem"
          volumeGap="0.375rem"
          buttonsSocialLogoFlowWidth="1.25rem"
          buttonsSocialLogoFlowHeight="1.25rem"
          priceFontSize="0.875rem"
          priceLineHeight="1.313rem"
          nameLeft="6.375rem"
          nameFontSize="1rem"
          nameLineHeight="1.5rem"
          artIconLeft="1.875rem"
          artIconWidth="3.375rem"
          artIconHeight="3.375rem"
          numberLeft="0rem"
          numberFontSize="0.875rem"
          numberLineHeight="1.313rem"
        />
        <TopCollectionItem
          buttonsSocialLogoFlow="/buttons-social--logo--tezos1.svg"
          price="3355.20"
          name1="Brick-and-Mortar Travails"
          art="/art@2x.png"
          number="8"
          authorWebItemV1OnLiWidth="32.03%"
          authorWebItemV1OnLiHeight="24.77%"
          authorWebItemV1OnLiPosition="absolute"
          authorWebItemV1OnLiTop="37.61%"
          authorWebItemV1OnLiRight="0%"
          authorWebItemV1OnLiBottom="37.61%"
          authorWebItemV1OnLiLeft="67.97%"
          volumeLeft="6.375rem"
          volumeGap="0.375rem"
          buttonsSocialLogoFlowWidth="1.25rem"
          buttonsSocialLogoFlowHeight="1.25rem"
          priceFontSize="0.875rem"
          priceLineHeight="1.313rem"
          nameLeft="6.375rem"
          nameFontSize="1rem"
          nameLineHeight="1.5rem"
          artIconLeft="1.875rem"
          artIconWidth="3.375rem"
          artIconHeight="3.375rem"
          numberLeft="0rem"
          numberFontSize="0.875rem"
          numberLineHeight="1.313rem"
        />
        <TopCollectionItem
          buttonsSocialLogoFlow="/buttons-social--logo--ethereum@2x.png"
          price="33457.59 "
          name1="RTFKT CloneX Mintvial"
          art="/art@2x.png"
          number="3"
          authorWebItemV1OnLiWidth="32.03%"
          authorWebItemV1OnLiHeight="24.77%"
          authorWebItemV1OnLiPosition="absolute"
          authorWebItemV1OnLiTop="75.23%"
          authorWebItemV1OnLiRight="67.97%"
          authorWebItemV1OnLiBottom="0%"
          authorWebItemV1OnLiLeft="0%"
          volumeLeft="6.375rem"
          volumeGap="0.375rem"
          buttonsSocialLogoFlowWidth="1.25rem"
          buttonsSocialLogoFlowHeight="1.25rem"
          priceFontSize="0.875rem"
          priceLineHeight="1.313rem"
          nameLeft="6.375rem"
          nameFontSize="1rem"
          nameLineHeight="1.5rem"
          artIconLeft="1.875rem"
          artIconWidth="3.375rem"
          artIconHeight="3.375rem"
          numberLeft="0rem"
          numberFontSize="0.875rem"
          numberLineHeight="1.313rem"
        />
        <TopCollectionItem
          buttonsSocialLogoFlow="/buttons-social--logo--ethereum@2x.png"
          price="13457.59 "
          name1="Worldwide Webb Land"
          art="/art@2x.png"
          number="7"
          authorWebItemV1OnLiWidth="32.03%"
          authorWebItemV1OnLiHeight="24.77%"
          authorWebItemV1OnLiPosition="absolute"
          authorWebItemV1OnLiTop="0%"
          authorWebItemV1OnLiRight="0%"
          authorWebItemV1OnLiBottom="75.23%"
          authorWebItemV1OnLiLeft="67.97%"
          volumeLeft="6.375rem"
          volumeGap="0.375rem"
          buttonsSocialLogoFlowWidth="1.25rem"
          buttonsSocialLogoFlowHeight="1.25rem"
          priceFontSize="0.875rem"
          priceLineHeight="1.313rem"
          nameLeft="6.375rem"
          nameFontSize="1rem"
          nameLineHeight="1.5rem"
          artIconLeft="1.875rem"
          artIconWidth="3.375rem"
          artIconHeight="3.375rem"
          numberLeft="0rem"
          numberFontSize="0.875rem"
          numberLineHeight="1.313rem"
        />
        <TopCollectionItem
          buttonsSocialLogoFlow="/buttons-social--logo--flow@2x.png"
          price="19,320.00 "
          name1="Chromie Squiggle by Snowfro"
          art="/art@2x.png"
          number="4"
          authorWebItemV1OnLiWidth="32.03%"
          authorWebItemV1OnLiHeight="24.77%"
          authorWebItemV1OnLiPosition="absolute"
          authorWebItemV1OnLiTop="0%"
          authorWebItemV1OnLiRight="34.06%"
          authorWebItemV1OnLiBottom="75.23%"
          authorWebItemV1OnLiLeft="33.91%"
          volumeLeft="6.375rem"
          volumeGap="0.375rem"
          buttonsSocialLogoFlowWidth="1.25rem"
          buttonsSocialLogoFlowHeight="1.25rem"
          priceFontSize="0.875rem"
          priceLineHeight="1.313rem"
          nameLeft="6.375rem"
          nameFontSize="1rem"
          nameLineHeight="1.5rem"
          artIconLeft="1.875rem"
          artIconWidth="3.375rem"
          artIconHeight="3.375rem"
          numberLeft="0rem"
          numberFontSize="0.875rem"
          numberLineHeight="1.313rem"
        />
        <TopCollectionItem
          buttonsSocialLogoFlow="/buttons-social--logo--flow@2x.png"
          price="10,450.00 "
          name1="Bored Ape Yacht Club"
          art="/art@2x.png"
          number="1"
          authorWebItemV1OnLiWidth="32.03%"
          authorWebItemV1OnLiHeight="24.77%"
          authorWebItemV1OnLiPosition="absolute"
          authorWebItemV1OnLiTop="0%"
          authorWebItemV1OnLiRight="67.97%"
          authorWebItemV1OnLiBottom="75.23%"
          authorWebItemV1OnLiLeft="0%"
          volumeLeft="6.375rem"
          volumeGap="0.375rem"
          buttonsSocialLogoFlowWidth="1.25rem"
          buttonsSocialLogoFlowHeight="1.25rem"
          priceFontSize="0.875rem"
          priceLineHeight="1.313rem"
          nameLeft="6.375rem"
          nameFontSize="1rem"
          nameLineHeight="1.5rem"
          artIconLeft="1.875rem"
          artIconWidth="3.375rem"
          artIconHeight="3.375rem"
          numberLeft="0rem"
          numberFontSize="0.875rem"
          numberLineHeight="1.313rem"
        />
      </div>
      <div className="absolute top-[0rem] right-[0rem] flex flex-row items-center justify-end gap-[0.375rem]">
        <CollectionFilterSelected
          bgHover="/bg-hover.svg"
          tag="1 Day"
          elementTags00D066SoftWidth="5.875rem"
          elementTags00D066SoftHeight="2.25rem"
          elementTags00D066SoftPosition="relative"
          tagLeft="32.66%"
          tagFontSize="0.75rem"
          tagLineHeight="1.125rem"
        />
        <CollectionFilter
          bgHover="/bg-hover1.svg"
          tag="7 Days"
          elementTagsF5F5FAOutlinWidth="5.875rem"
          elementTagsF5F5FAOutlinHeight="2.25rem"
          elementTagsF5F5FAOutlinPosition="relative"
          tagLeft="1.656rem"
          tagFontSize="0.75rem"
          tagLineHeight="1.125rem"
        />
        <CollectionFilter
          bgHover="/bg-hover1.svg"
          tag="30 Days"
          elementTagsF5F5FAOutlinWidth="5.875rem"
          elementTagsF5F5FAOutlinHeight="2.25rem"
          elementTagsF5F5FAOutlinPosition="relative"
          tagLeft="1.406rem"
          tagFontSize="0.75rem"
          tagLineHeight="1.125rem"
        />
      </div>
    </div>
  );
};

export default Collections;
